# coding: utf-8

SUBS = {}
SUBS['akan'] = [
  (u'nyaeew\u0254ee', u'nyaee'),
  (u'b\u025bnyaw\u0254', u'b\u025bnya'),
  (u'w\u0254w\u0254', u'w\u0254'),
  (u'oana yɛ', u'oana nye'),
  (u'ba ha', 'bra ha'),
  ('_', ''),
]
SUBS['chewa'] = [
  ('_', ''),
  ('ya la', 'ya'),
]
SUBS['english'] = [
  (' : ', ': '),
  (' a i', ' an i'),
  ('ambe', 'am'),
  ('arebe', 'are'),
  ('isbe', 'is'),
  ('wasbe', 'was'),
  ('werebe', 'were'),
  ('beated', 'beat'),
  ('biteed', 'bit'),
  ('blowed', 'blew'),
  ('bringed', 'brought'),
  ('builded', 'built'),
  ('catched', 'caught'),
  ('catchs', 'catches'),
  ('childs', 'children'),
  ('doed', 'did'),
  ('falled', 'fell'),
  ('finded', 'found'),
  ('fys', 'fies'),
  ('haveed', 'had'),
  ('haves', 'has'),
  ('hise', 'his'),
  ('how you', 'how do you'),
  ('keeped', 'kept'),
  ('leaded', 'led'),
  ('leted', 'let'),
  ('leting', 'letting'),
  ('meeted', 'met'),
  ('sayed', 'said'),
  ('sended', 'sent'),
  ('stealed', 'stole'),
  ('stoping', 'stopping'),
  ('stoped', 'stopped'),
  ('thinked', 'thought'),
  ('throwed', 'threw'),
  ('touchs', 'touches'),
  ('I be ', 'I am '),
  ('You be ', 'You are '),
  (' bes ', ' is '),
  ('We be ', 'We are '),
  ('You be ', 'You are '),
  ('you why', 'why do you'),
  ('They be ', 'They are '),
  ("(don't) be able to", '(not) be able to'),
  ('gos', 'goes'),
  ('eed', 'ed'),
  ('e\\textbf{ee}', 'e\\textbf{e}'),
  ('nn}n', 'n}n'),
  ('nn)}n', 'n)}n'),
  ('being able', 'able'),
  ('baths', 'bathes'),
  ('buyed', 'bought'),
  ('claped', 'clapped'),
  ('claping', 'clapping'),
  (' comed', ' came'),
  ('comed', 'came'),
  ('drinked', 'drank'),
  ('drived', 'drove'),
  ('ryed', 'ried'),
  ('rys', 'ries'),
  ('cuting', 'cutting'),
  ('cuted', 'cut'),
  ('lys',  'lies'),
  ('geting', 'getting'),
  (' geted', ' gotten'),
  ('geted', 'got'),
  ('have gived', 'have given'),
  ('gived', 'gave'),
  ('dieing', 'dying'),
  ('eing', 'ing'),
  ('bing', 'being'),
  ('have bed', 'have been'),
  ('I bed', 'I was'),
  ('seing', 'seeing'),
  ('diging', 'digging'),
  ('diged', 'dug'),
  (' drinked', ' drunk'),
  ('drinked', 'drank'),
  ('have eated', 'have eaten'),
  (' eated', ' ate'),
  ('have flyed', 'have flown'),
  ('flyed', 'flew'),
  ('have goed', 'have gone'),
  (' goed', ' went'),
  ('grinded', 'ground'),
  ('heared', 'heard'),
  (' hided', ' hidden'),
  ('hided', 'hid'),
  ('hiting', 'hitting'),
  ('hited', 'hit'),
  ('holded', 'held'),
  ('have knowed', 'have known'),
  ('knowed', 'knew'),
  ('maked', 'made'),
  ('{ned}', '{need}'),
  ('neded', 'needed'),
  (' ned', ' need'),
  ('readed', 'read'),
  ('have rised', 'have risen'),
  ('rised', 'rose'),
  ('runing', 'running'),
  ('have runed', 'have run'),
  ('runed', 'ran'),
  ('have seed', 'have seen'),
  ('seed', 'saw'),
  ('selled', 'sold'),
  ('have shaked', 'have shaken'),
  ('shaked', 'shook'),
  ('have singed', 'have sung'),
  ('singed', 'sang'),
  ('siting', 'sitting'),
  ('sited', 'sat'),
  ('sleeped', 'slept'),
  ('standed', 'stood'),
  (' sowed', ' sown'),
  ('have speaked', 'have spoken'),
  ('speaked', 'spoke'),
  ('swiming', 'swimming'),
  ('swimed', 'swam'),
  ('have taked', 'have taken'),
  ('had taked', 'had taken'),
  ('taked', 'took'),
  ('teached', 'taught'),
  ('wining', 'winning'),
  ('wined', 'won'),
  ('not writed', 'not written'),
  ('have writed', 'have written'),
  ('had writed', 'had written'),
  ('writed', 'wrote'),
  ('buyed', 'bought'),
  ('comed', 'came'),
  ('have came', 'have come'),
  ('not came', 'not come'),
  ('ryed', 'ried'),
  ('cuting', 'cutting'),
  ('cuted', 'cut'),
  ('gived', 'gave'),
  ('dieing', 'dying'),
  ('eing', 'ing'),
  ('bing', 'being'),
  (' bed', ' were'),
  ('have {bed', 'have {been'),
  ('seing', 'seeing'),
  ('diging', 'digging'),
  ('diged', 'digged'),
  ('have eated', 'have eaten'),
  ('not eated', 'not eaten'),
  ('have flyed', 'have flown'),
  ('not flyed', 'not flown'),
  ('standed', 'stood'),
  (' sowed', ' sown'),
  (' speaked', ' spoken'),
  ('speaked', 'spoke'),
  ('swiming', 'swimming'),
  ('swimed', 'swam'),
  ('have taked', 'have taken'),
  ('had taked', 'had taken'),
  ('taked', 'took'),
  ('teached', 'taught'),
  ('wining', 'winning'),
  ('wined', 'won'),
  ('not writed', 'not written'),
  ('have writed', 'have written'),
  ('had writed', 'had written'),
  ('writed', 'wrote'),
  ('watchs', 'watches'),
  ('flyed', 'flew'),
  ('nb', 'mb'),
  ('nf', 'mf'),
  ('np', 'mp'),
  ('{n}b', '{m}b'),
  ('{n}f', '{m}f'),
  ('{n}p', '{m}p'),
  ('nn}b', 'mm}b'),
  ('nn}f', 'mm}f'),
  ('nn}p', 'mm}p'),
  ('(nn)}b', '(mm)}b'),
  ('(nn)}f', '(mm)}f'),
  ('nn}p', 'mm}p'),
  ('(nn)}b', '(mm)}b'),
  ('(nn)}f', '(mm)}f'),
  ('(nn)}p', '(mm)}p'),
  ('yous', 'you'),
]

SUBS['french'] = {
  ('oiez', 'oyez'),
  ('oions', 'oyons'),
  ('iiez', 'yiez'),
  ('iions', 'yions'),
  ('oia', 'oya'),
  ('je ai', "j'ai"),
  ('la livre', 'le livre'),
  ('ma livre', 'mon livre'),
}
SUBS['DEPRECATED_french'] = [
  ('I am', 'je'),
  ('you and you are', 'vous'),
  ('you are', 'tu'),
  ('s/he is', 'il/elle'),
  ('we are', 'nous'),
  ('they are', 'ils/elles'),
  ('I will', 'je vais'),
  ('you and you will', 'vous allez'),
  ('you will', 'tu vas'),
  ('s/he will', 'il/elle va'),
  ('we will', 'nous allons'),
  ('they will', 'ils/elles vont'),
  ('I', 'je'),
  ('you and you', 'vous'),
  ('you', 'tu'),
  ('s/he', 'il/elle'),
  ('we', 'nous'),
  ('they', 'ils/elles'),
  ('Today', "Aujourd'hui"),
  ('YESTERDAY', 'HIER'),
  ('TOMORROW', 'DEMAIN'),
  ('TODAY', u'AUJOURD\'HUI'),
  ('Past', u'Passé'),
  ('Future', u'Futur'),
  (u'ége ]', u'ège ]'),
  (u'éges ]', u'èges ]'),
  (u'égent ]', u'ègent ]'),
  (u'gons', u'geons'),
  ('je avoe', 'j\'ai'),
  ('avoe', 'a'),
  ('avoons', 'avons'),
  ('az', 'avez'),
  ('s ant', 's ont'),
  (u'avoé', 'eu'),
  ('airai', 'aurai'),
  ('ara', 'aura'),
  ('aron', 'auron'),
  ('arez', 'aurez'),
  ('ae ]', 'ais ]'),
]
SUBS['gbe'] = [
  ('_', ''),
  (u'nyenyɛ', 'nye'),
]
SUBS['german'] = [
  ('_', ''),
  ('gehte', 'ging'),
  ('gn', 'gen'),
  ('meine buch', 'mein buch'),
]
SUBS['gikuyu'] = [
  ('_', ''),
]
SUBS['hausa'] = [
  ('-', 'n'),
]
SUBS['igbo'] = [
  ('_', ''),
]
SUBS['kongo'] = [
  ('_', ''),
]
SUBS['lingala'] = [
  ('_', ''),
  ('ani azali ', 'ani aza '),
  ('lii', 'lei'),
]
SUBS['luganda'] = [
  ('_', ''),
  ('abeera ani', 'y\'ani'),
]
SUBS['luwo'] = [
  ('_', ''),
  ('oin ng\'a', ', en ng\'a'),
]
SUBS['malagasy'] = [
  ('_', ''),
  ('iza mdia', 'iza moa i'),
  ('mtia', 'tia an\'i'),
  ('andro tsirairay', 'isan\'andro'),
  ('mdia olombelona', 'olona'),
]
SUBS['oromo'] = [
  ('chdh', 'dh'),
  ('chtt', 'tt'),
  ('cht', 't'),
  ('chnn', 'nn'),
  ('chn', 'n'),
  ('_', ''),
]
SUBS['shona'] = [
  ('_', ''),
  ('noria', 'ri'),
  #('anouvea', 'ari'),
  #('ndinouvea', 'ndiri'),
]
SUBS['spanish'] = [
  ('_', ''),
  ('la libro', 'el libro'),
]
SUBS['swahili'] = [
  ('_', ''),
  ('Nani anania', 'Ambao ni'),
  ('ya angu', 'yangu'),
  ('ya ake', 'yake'),
  ('siku kila', 'kila siku'),
]
SUBS['tigrinya'] = [
  ('_', ''),
]
SUBS['ururimi'] = [  # longest substring matches first
  ('_', ''),
  ('amai', 'ama'),
  ('nra', 'nda'),
  ('agende', 'agiye'),  # Past tense of verb kugenda
  ('akore', 'akoze'), # Past tense of verb gukora
  #('ua', 'wa'),
  ('turaba', 'ni'),
  ('uraba', 'ni'),
  ('ndaba', 'ni'),
  ('baraba', 'ni'),
  ('muraba', 'ni'),
  ('araba', 'ni'),
]
SUBS['zulu'] = [
  ('_', ''),
]
